language: r
cache: packages

before_install:
  - if $RUN_SETUP; then chmod +x travissetup.sh; ./travissetup.sh;
    else echo hi there; fi

r_packages:
  - covr

matrix:
  include:
    - r: release
      os: linux
      dist: xenial
      env: RUN_SETUP=false
    - r: release
      os: linux
      dist: bionic # https://docs.travis-ci.com/user/reference/bionic/
      env: RUN_SETUP=true
    - r: release
      os: linux
      dist: bionic # https://docs.travis-ci.com/user/reference/bionic/
      env: 
        - RUN_SETUP=true
        - TZ="Asia/Kathmandu"
        - XLCONNECT_JAVA_REPO_URL="https://jcenter.bintray.com"
    - r: release
      os: linux
      dist: bionic # https://docs.travis-ci.com/user/reference/bionic/
      env: 
        - RUN_SETUP=true
        - TZ="Canada/Newfoundland"
    - r: release
      os: linux
      dist: bionic # https://docs.travis-ci.com/user/reference/bionic/
      env: 
        - RUN_SETUP=true
        - TZ="Pacific/Marquesas"
    # - r: release
    #   os: osx
    #   osx_image: xcode9.4 # https://docs.travis-ci.com/user/reference/osx/
    #   env: RUN_SETUP=true
    - r: devel
      os: linux
      dist: xenial
      env: 
        - RUN_SETUP=false
        - XLCONNECT_JAVA_REPO_URL="https://jcenter.bintray.com"
    - r: devel
      os: linux
      dist: bionic
      env: RUN_SETUP=false
    # - r: oldrel
    #   os: osx
    #   osx_image: xcode9.4
    #   env: RUN_SETUP=true
    - r: oldrel
      os: linux
      dist: xenial
      env: RUN_SETUP=false
    - r: oldrel
      os: linux
      dist: bionic
      env: 
        - RUN_SETUP=false
        - XLCONNECT_JAVA_REPO_URL="https://jcenter.bintray.com"
    - r: 3.2.5
      os: linux
      dist: bionic
      env: RUN_SETUP=false

script:
  - |
    date
    java -version
    R CMD build --compact-vignettes=both --md5 .
    export FULL_TEST_SUITE=1
    R CMD check XLConnect*tar.gz
    travis_wait 30 travis_retry Rscript -e 'covr::codecov()'

notifications:
  slack:
    secure: THJdpmjCPabFEf6AQT/hLEH1e+7scOwyfPY5D0dRWaJF53fbqrfj/krYdhPeBt/EMFZqOh9ERO61DCl+OMPqsBpisbzPxR/+qv9hJN4A4Dhx6lr67pmmCOq0LcaZ7yV68H0y0yNrvrOkFV8yNiDBGC5VzmE3ywBJTB5x6krBrsg=
